### ISSUE TITLE
ggplot_calendar_heatmap() modifies data without warning 

### ISSUE THREAD

**Issue by t-kalinowski** [AtherEnergy/ggTimeSeries#1]
Hello, thank you for the helpful package. 

Calling `ggplot_calendar_heatmap()` on a dataframe coerces it to class data.table permanently. This is surprising and unexpected behavior. 

This also breaks code, because data.table overrides magritter / dplyr pipes, and completely changes the way the "." placeholder is treated.

Please make it so that `ggplot_calendar_heatmap()` does not modify data (as it shouldn't), or at a minimum, warn users with a message() that their data is being modified, or require them to convert to a data.table themselves.

**Comment by t-kalinowski** [comment]
wrapping the incoming data in `as.data.frame()` seems to stop the `setDT()` from reaching back and modifying the data.

**Comment by dasather** [comment]
Closed with commit 8ce41629d45b6cb2a401db378289f687d1e99914
