### ISSUE TITLE
Citation info

### ISSUE THREAD

**Issue by TY-Cheng** [AtherEnergy/ggTimeSeries#10]
Would be better if available BibTeX citation info could be provided.

**Comment by dasather** [comment]
> library(ggTimeSeries)
> citation("ggTimeSeries")

To cite package ‘ggTimeSeries’ in publications use:

  Aditya Kothari (2018). ggTimeSeries: Time Series Visualisations Using the Grammar of Graphics. R package version 1.0.1.
  https://CRAN.R-project.org/package=ggTimeSeries

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {ggTimeSeries: Time Series Visualisations Using the Grammar of Graphics},
    author = {Aditya Kothari},
    year = {2018},
    note = {R package version 1.0.1},
    url = {https://CRAN.R-project.org/package=ggTimeSeries},
  }
